export type FieldType =
  | "text"
  | "email"
  | "textarea"
  | "number"
  | "money"
  | "date"
  | "time"
  | "boolean"
  | "select"
  | "reference";

export interface FieldDef {
  name: string;
  label: string;
  type: FieldType;
  options?: string[];
  ref?: string;
  refLabel?: string;
  required?: boolean;
  readOnly?: boolean;
  gridSpan?: 1 | 2;
  hint?: string;
}

export interface ResourceConfig {
  key: string;
  table: string;
  label: string;
  plural: string;
  description?: string;
  fields: FieldDef[];
  tableColumns: string[];
  searchCols: string[];
  orderBy: string;
  orderDir?: "ASC" | "DESC";
  insertDefaults?: Record<string, unknown>;
}

const PAYMENT_STATUS = ["Pending", "Partial", "Paid", "Settled", "Unpaid"];
const STATUS = ["Active", "Inactive", "Pending", "Completed", "Cancelled"];
const PAYMENT_METHOD = ["Cash", "UPI", "Card", "Bank Transfer", "Cheque", "Other"];

const VEHICLE_STATUS = ["On Road", "Available", "Under Maintenance", "In Garage", "Retired"];
const VEHICLE_TYPES = [
  "Hatchback",
  "Sedan",
  "Premium Sedan",
  "SUV",
  "MUV",
  "Innova",
  "Innova Crysta",
  "Tempo Traveller",
  "Mini Bus",
];
const EXPENSE_CATEGORIES = [
  "Petrol",
  "Fuel",
  "Home",
  "Office",
  "Driver",
  "Vehicle",
  "Repairs",
  "Toll",
  "Rent",
  "Loan",
  "Recharge",
  "Miscellaneous",
  "Other",
];

export const BUSINESS_RESOURCES: Record<string, ResourceConfig> = {
  customers: {
    key: "customers",
    table: "customers",
    label: "Customer",
    plural: "Customers",
    description: "Customers registered in the business day book and bookings with auto mobile-based Customer ID.",
    fields: [
      {
        name: "customer_code",
        label: "Customer Code",
        type: "text",
        required: false,
        hint: "Auto-generated from mobile number e.g. CUST-9876543210",
      },
      {
        name: "family_suffix",
        label: "Family Member Suffix (1 to 9)",
        type: "select",
        options: ["Main (Primary)", "-1", "-2", "-3", "-4", "-5", "-6", "-7", "-8", "-9"],
        hint: "Suffix for family members sharing the same mobile number e.g. CUST-9876543210-1",
      },
      { name: "name", label: "Customer Name", type: "text", required: true },
      { name: "phone", label: "Phone Number", type: "text", required: true },
      { name: "alternate_phone", label: "Alternate Phone", type: "text" },
      { name: "email", label: "Email", type: "email" },
      { name: "address", label: "Address", type: "textarea" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: ["customer_code", "family_suffix", "name", "phone", "city", "created_at"],
    searchCols: ["name", "phone", "customer_code", "city", "state", "email"],
    orderBy: "id",
    orderDir: "DESC",
  },

  drivers: {
    key: "drivers",
    table: "drivers",
    label: "Driver Account",
    plural: "Drivers",
    description: "Driver accounts with login credentials (User ID / Email, Password) and section permissions.",
    fields: [
      { name: "driver_name", label: "Driver Name", type: "text", required: true },
      { name: "email", label: "Email / User ID (For Login)", type: "email", required: true, hint: "e.g. driver.ramesh@fortunetourism.com" },
      { name: "password", label: "Password (For Login)", type: "text", required: true, hint: "e.g. DriverSecret123" },
      { name: "phone", label: "Phone Number", type: "text", required: true },
      { name: "access_pin", label: "Access PIN / Code", type: "text", hint: "e.g. 1234" },
      {
        name: "allowed_sections",
        label: "Allowed Sections (Permissions)",
        type: "text",
        hint: "Select which sections this driver can view and edit",
      },
      { name: "company_name", label: "Company Name", type: "text" },
      { name: "alternate_phone", label: "Alternate Phone", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "area", label: "Area", type: "text" },
      { name: "vehicle_type", label: "Vehicle Type", type: "select", options: VEHICLE_TYPES },
      {
        name: "vehicle_id",
        label: "Assigned Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      { name: "status", label: "Status", type: "select", options: STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: ["driver_name", "email", "phone", "password", "allowed_sections", "status"],
    searchCols: ["driver_name", "email", "phone", "city", "company_name"],
    orderBy: "id",
    orderDir: "DESC",
  },

  accounts: {
    key: "accounts",
    table: "accounts",
    label: "Account",
    plural: "Accounts",
    description: "Business accounts used for expenses and transactions.",
    fields: [
      { name: "account_name", label: "Account Name", type: "text", required: true },
      {
        name: "account_type",
        label: "Account Type",
        type: "select",
        options: ["Bank", "Cash", "Credit", "Loan", "Other"],
      },
      { name: "opening_balance", label: "Opening Balance", type: "money" },
      { name: "status", label: "Status", type: "select", options: STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: ["account_name", "account_type", "opening_balance", "status"],
    searchCols: ["account_name", "account_type"],
    orderBy: "id",
    orderDir: "DESC",
  },

  day_book_entries: {
    key: "day_book_entries",
    table: "day_book_entries",
    label: "Day Book Entry",
    plural: "Day Book",
    description: "The daily bookings register (like the Excel day book sheet).",
    fields: [
      { name: "serial_number", label: "Serial No.", type: "text" },
      { name: "booking_date", label: "Booking Date", type: "date" },
      { name: "travel_date", label: "Travel Date", type: "date" },
      { name: "travel_by", label: "Travel By", type: "text", hint: "Vehicle / type used" },
      { name: "passenger_name", label: "Passenger Name", type: "text", required: true },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "passenger_phone", label: "Passenger Phone", type: "text" },
      { name: "from_location", label: "From", type: "text" },
      { name: "to_location", label: "To", type: "text" },
      { name: "pickup_location", label: "Pickup Location", type: "text" },
      { name: "booking_amount", label: "Booking Amount", type: "money" },
      { name: "office_advance", label: "Office Advance", type: "money" },
      { name: "due_amount", label: "Due Amount", type: "money" },
      { name: "expense_amount", label: "Expense Amount", type: "money" },
      { name: "total_amount", label: "Total Amount", type: "money" },
      { name: "booking_reference", label: "Booking Reference", type: "text" },
      { name: "payment_method", label: "Payment Method", type: "select", options: PAYMENT_METHOD },
      { name: "status", label: "Status", type: "select", options: STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "booking_date",
      "serial_number",
      "passenger_name",
      "from_location",
      "to_location",
      "booking_amount",
      "due_amount",
      "status",
    ],
    searchCols: [
      "passenger_name",
      "serial_number",
      "booking_reference",
      "from_location",
      "to_location",
      "passenger_phone",
    ],
    orderBy: "id",
    orderDir: "DESC",
  },

  cab_bookings: {
    key: "cab_bookings",
    table: "cab_bookings",
    label: "Cab Booking",
    plural: "Cab Bookings",
    description: "One-way / round-trip cab bookings with driver & vehicle.",
    fields: [
      { name: "booking_number", label: "Booking Number", type: "text" },
      { name: "booking_date", label: "Booking Date", type: "date" },
      { name: "travel_date", label: "Travel Date", type: "date" },
      { name: "from_location", label: "From", type: "text" },
      { name: "to_location", label: "To", type: "text" },
      { name: "pickup_time", label: "Pickup Time", type: "time" },
      { name: "passenger_name", label: "Passenger Name", type: "text", required: true },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "passenger_phone", label: "Passenger Phone", type: "text" },
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      { name: "vehicle_number", label: "Vehicle Number", type: "text" },
      { name: "vehicle_type", label: "Vehicle Type", type: "select", options: VEHICLE_TYPES },
      {
        name: "driver_id",
        label: "Driver",
        type: "reference",
        ref: "drivers",
        refLabel: "driver_name",
      },
      { name: "driver_phone", label: "Driver Phone", type: "text" },
      { name: "due_amount", label: "Due Amount", type: "money" },
      { name: "to_pay", label: "To Pay", type: "money" },
      { name: "settled_amount", label: "Settled Amount", type: "money" },
      { name: "payment_date", label: "Payment Date", type: "date" },
      { name: "payment_status", label: "Payment Status", type: "select", options: PAYMENT_STATUS },
      { name: "payment_method", label: "Payment Method", type: "select", options: PAYMENT_METHOD },
      { name: "status", label: "Status", type: "select", options: STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "booking_number",
      "booking_date",
      "travel_date",
      "passenger_name",
      "from_location",
      "to_location",
      "vehicle_number",
      "due_amount",
      "payment_status",
    ],
    searchCols: [
      "booking_number",
      "passenger_name",
      "passenger_phone",
      "from_location",
      "to_location",
      "vehicle_number",
    ],
    orderBy: "id",
    orderDir: "DESC",
  },

  package_trips: {
    key: "package_trips",
    table: "package_trips",
    label: "Package Trip",
    plural: "Package Trips",
    description: "Multi-day tour package trips with run-km billing.",
    fields: [
      { name: "trip_number", label: "Trip Number", type: "text" },
      { name: "tour_name", label: "Tour Name", type: "text", required: true },
      { name: "journey_date", label: "Journey Date", type: "date" },
      { name: "return_date", label: "Return Date", type: "date" },
      { name: "passenger_name", label: "Passenger Name", type: "text" },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "passenger_phone", label: "Passenger Phone", type: "text" },
      { name: "car_type", label: "Car Type", type: "select", options: VEHICLE_TYPES },
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      {
        name: "driver_id",
        label: "Driver",
        type: "reference",
        ref: "drivers",
        refLabel: "driver_name",
      },
      { name: "driver_phone", label: "Driver Phone", type: "text" },
      { name: "pickup_location", label: "Pickup Location", type: "text" },
      { name: "drop_location", label: "Drop Location", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "temporary_permit", label: "Temporary Permit", type: "text" },
      { name: "total_run_km", label: "Total Run (KM)", type: "number" },
      { name: "per_km_rate", label: "Per KM Rate", type: "money" },
      { name: "bata", label: "Bata (Driver)", type: "money" },
      { name: "toll_expense", label: "Toll Expense", type: "money" },
      { name: "due_amount", label: "Due Amount", type: "money" },
      { name: "paid_amount", label: "Paid Amount", type: "money" },
      { name: "settled_date", label: "Settled Date", type: "date" },
      { name: "total_cost", label: "Total Cost", type: "money" },
      { name: "remaining_amount", label: "Remaining", type: "money", readOnly: true },
      { name: "payment_phone", label: "Payment Phone", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "trip_number",
      "tour_name",
      "journey_date",
      "passenger_name",
      "car_type",
      "due_amount",
      "paid_amount",
      "remaining_amount",
    ],
    searchCols: ["trip_number", "tour_name", "passenger_name", "passenger_phone"],
    orderBy: "id",
    orderDir: "DESC",
  },

  hourly_bookings: {
    key: "hourly_bookings",
    table: "hourly_bookings",
    label: "Hourly Booking",
    plural: "Hourly Bookings",
    description: "Local city hourly package bookings.",
    fields: [
      { name: "booking_number", label: "Booking Number", type: "text" },
      { name: "booking_date", label: "Booking Date", type: "date" },
      { name: "travel_date", label: "Travel Date", type: "date" },
      { name: "passenger_name", label: "Passenger Name", type: "text", required: true },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "phone", label: "Phone", type: "text" },
      { name: "from_location", label: "From", type: "text" },
      { name: "to_location", label: "To", type: "text" },
      { name: "hours", label: "Hours", type: "number" },
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      {
        name: "driver_id",
        label: "Driver",
        type: "reference",
        ref: "drivers",
        refLabel: "driver_name",
      },
      { name: "taxi_number", label: "Taxi Number", type: "text" },
      { name: "toll", label: "Toll", type: "money" },
      { name: "boarding", label: "Boarding", type: "money" },
      { name: "amount", label: "Amount", type: "money" },
      { name: "payment_status", label: "Payment Status", type: "select", options: PAYMENT_STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "booking_number",
      "booking_date",
      "travel_date",
      "passenger_name",
      "from_location",
      "to_location",
      "hours",
      "amount",
      "payment_status",
    ],
    searchCols: ["booking_number", "passenger_name", "phone", "from_location", "to_location"],
    orderBy: "id",
    orderDir: "DESC",
  },

  expenses: {
    key: "expenses",
    table: "expenses",
    label: "Expense",
    plural: "Expenses",
    description: "Business expenses — petrol, repairs, home/office, etc.",
    fields: [
      { name: "expense_date", label: "Expense Date", type: "date" },
      { name: "category", label: "Category", type: "select", options: EXPENSE_CATEGORIES },
      { name: "description", label: "Description", type: "text", required: true },
      { name: "paid_to", label: "Paid To", type: "text" },
      { name: "amount", label: "Amount", type: "money", required: true },
      { name: "payment_method", label: "Payment Method", type: "select", options: PAYMENT_METHOD },
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      {
        name: "driver_id",
        label: "Driver",
        type: "reference",
        ref: "drivers",
        refLabel: "driver_name",
      },
      {
        name: "account_id",
        label: "Account",
        type: "reference",
        ref: "accounts",
        refLabel: "account_name",
      },
      { name: "reference", label: "Reference", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "expense_date",
      "category",
      "description",
      "paid_to",
      "amount",
      "payment_method",
    ],
    searchCols: ["description", "paid_to", "reference", "category"],
    orderBy: "id",
    orderDir: "DESC",
  },

  account_transactions: {
    key: "account_transactions",
    table: "account_transactions",
    label: "Account Transaction",
    plural: "Account Transactions",
    description: "Debit / credit ledger entries for each account.",
    fields: [
      {
        name: "account_id",
        label: "Account",
        type: "reference",
        ref: "accounts",
        refLabel: "account_name",
        required: true,
      },
      { name: "transaction_date", label: "Transaction Date", type: "date" },
      {
        name: "transaction_type",
        label: "Type",
        type: "select",
        options: ["Debit", "Credit", "Transfer", "Expense", "Payment"],
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "debit", label: "Debit", type: "money" },
      { name: "credit", label: "Credit", type: "money" },
      { name: "amount", label: "Amount", type: "money" },
      { name: "payment_method", label: "Payment Method", type: "select", options: PAYMENT_METHOD },
      { name: "reference", label: "Reference", type: "text" },
      { name: "person_name", label: "Person", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "transaction_date",
      "account_id",
      "transaction_type",
      "debit",
      "credit",
      "description",
    ],
    searchCols: ["description", "reference", "person_name"],
    orderBy: "id",
    orderDir: "DESC",
  },

  payments: {
    key: "payments",
    table: "payments",
    label: "Payment",
    plural: "Payments",
    description: "Centralized record of money received / paid.",
    fields: [
      { name: "payment_date", label: "Payment Date", type: "date" },
      { name: "amount", label: "Amount", type: "money", required: true },
      { name: "payment_method", label: "Payment Method", type: "select", options: PAYMENT_METHOD },
      { name: "reference", label: "Reference", type: "text" },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      {
        name: "driver_id",
        label: "Driver",
        type: "reference",
        ref: "drivers",
        refLabel: "driver_name",
      },
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      { name: "booking_id", label: "Booking ID", type: "number" },
      { name: "trip_id", label: "Trip ID", type: "number" },
      {
        name: "account_id",
        label: "Account",
        type: "reference",
        ref: "accounts",
        refLabel: "account_name",
      },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "payment_date",
      "amount",
      "payment_method",
      "reference",
      "customer_id",
      "driver_id",
      "description",
    ],
    searchCols: ["reference", "description", "amount"],
    orderBy: "id",
    orderDir: "DESC",
  },

  outstanding_entries: {
    key: "outstanding_entries",
    table: "outstanding_entries",
    label: "Outstanding Entry",
    plural: "Outstanding",
    description: "Money owed by customers / to drivers or for bookings.",
    fields: [
      {
        name: "entity_type",
        label: "Entity Type",
        type: "select",
        options: ["Customer", "Driver", "Vehicle", "Booking"],
      },
      { name: "entity_id", label: "Entity ID", type: "number" },
      {
        name: "reference_type",
        label: "Reference Type",
        type: "select",
        options: [
          "Cab Booking",
          "Package Trip",
          "Hourly Booking",
          "Day Book",
          "Bus Booking",
          "Other",
        ],
      },
      { name: "reference_id", label: "Reference ID", type: "number" },
      { name: "original_amount", label: "Original Amount", type: "money", required: true },
      { name: "paid_amount", label: "Paid Amount", type: "money" },
      { name: "remaining_amount", label: "Remaining", type: "money", readOnly: true },
      { name: "due_date", label: "Due Date", type: "date" },
      {
        name: "status",
        label: "Status",
        type: "select",
        options: ["Open", "Partial", "Paid", "Overdue", "Closed"],
      },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "entity_type",
      "reference_type",
      "original_amount",
      "paid_amount",
      "remaining_amount",
      "due_date",
      "status",
    ],
    searchCols: ["reference_type", "notes"],
    orderBy: "id",
    orderDir: "DESC",
  },

  repairs: {
    key: "repairs",
    table: "repairs",
    label: "Repair",
    plural: "Repairs",
    description: "Vehicle repair & maintenance records with complete registration number.",
    fields: [
      {
        name: "vehicle_number",
        label: "Complete Car Registration Number",
        type: "text",
        required: true,
        hint: "Complete plate number e.g. KA 05 MN 1234",
      },
      {
        name: "vehicle_id",
        label: "Vehicle (Assigned)",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      { name: "repair_date", label: "Repair Date", type: "date" },
      { name: "garage", label: "Garage", type: "text" },
      { name: "part", label: "Part", type: "text" },
      { name: "amount", label: "Amount", type: "money", required: true },
      { name: "paid_by", label: "Paid By", type: "text" },
      { name: "payment_method", label: "Payment Method", type: "select", options: PAYMENT_METHOD },
      { name: "description", label: "Description", type: "textarea" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: ["vehicle_number", "repair_date", "garage", "part", "amount", "paid_by"],
    searchCols: ["vehicle_number", "garage", "part", "description"],
    orderBy: "id",
    orderDir: "DESC",
  },

  permits: {
    key: "permits",
    table: "permits",
    label: "Permit",
    plural: "Permits",
    description: "State / temporary permits for vehicles.",
    fields: [
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      {
        name: "permit_type",
        label: "Permit Type",
        type: "select",
        options: ["State", "Temporary", "National", "Taxi", "Other"],
      },
      { name: "state", label: "State", type: "text" },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "end_date", label: "End Date", type: "date" },
      { name: "amount", label: "Amount", type: "money" },
      { name: "payment_status", label: "Payment Status", type: "select", options: PAYMENT_STATUS },
      { name: "reference", label: "Reference", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: ["permit_type", "state", "start_date", "end_date", "amount", "payment_status"],
    searchCols: ["permit_type", "state", "reference"],
    orderBy: "id",
    orderDir: "DESC",
  },

  insurance_records: {
    key: "insurance_records",
    table: "insurance_records",
    label: "Insurance Record",
    plural: "Insurance",
    description: "Vehicle insurance policies.",
    fields: [
      {
        name: "vehicle_id",
        label: "Vehicle",
        type: "reference",
        ref: "vehicles",
        refLabel: "name",
      },
      { name: "provider", label: "Provider", type: "text" },
      { name: "policy_number", label: "Policy Number", type: "text" },
      {
        name: "insurance_type",
        label: "Type",
        type: "select",
        options: ["Comprehensive", "Third Party", "Own Damage", "Other"],
      },
      { name: "start_date", label: "Start Date", type: "date" },
      { name: "expiry_date", label: "Expiry Date", type: "date" },
      { name: "premium", label: "Premium", type: "money" },
      { name: "contact", label: "Contact", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "provider",
      "policy_number",
      "insurance_type",
      "start_date",
      "expiry_date",
      "premium",
    ],
    searchCols: ["provider", "policy_number"],
    orderBy: "id",
    orderDir: "DESC",
  },

  vehicle_forecasts: {
    key: "vehicle_forecasts",
    table: "vehicle_forecasts",
    label: "Vehicle Forecast",
    plural: "Vehicle Forecasts",
    description: "New vehicle EMI, debited months, late payment fines & automated PDF reports.",
    fields: [
      { name: "vehicle_type", label: "Vehicle Type", type: "select", options: VEHICLE_TYPES },
      { name: "car_model", label: "Car Model", type: "text", required: true },
      { name: "variant", label: "Variant", type: "text" },
      { name: "vehicle_price", label: "Vehicle Price", type: "money" },
      { name: "down_payment", label: "Down Payment", type: "money" },
      { name: "loan_amount", label: "Loan Amount", type: "money" },
      { name: "interest_rate", label: "Interest Rate (%)", type: "number" },
      { name: "loan_tenure", label: "Loan Tenure (Months)", type: "number" },
      { name: "emi", label: "EMI Amount", type: "money" },
      { name: "debited_months", label: "Debited Months Paid", type: "number", hint: "No. of months EMI already debited" },
      { name: "late_payment_fine_rate", label: "Late Fine Rate (%)", type: "number", hint: "Overdue fine percentage" },
      { name: "fine_amount", label: "Late Payment Fine Amount", type: "money" },
      { name: "total_due", label: "Total Due", type: "money" },
      { name: "engine_warranty", label: "Engine Warranty", type: "text" },
      { name: "km_warranty", label: "KM Warranty", type: "text" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "car_model",
      "vehicle_type",
      "vehicle_price",
      "loan_tenure",
      "emi",
      "debited_months",
      "fine_amount",
    ],
    searchCols: ["vehicle_type", "car_model", "variant"],
    orderBy: "id",
    orderDir: "DESC",
  },

  rto_agents: {
    key: "rto_agents",
    table: "rto_agents",
    label: "RTO Agent",
    plural: "RTO Agents",
    description: "RTO agents used for permits & vehicle documents.",
    fields: [
      { name: "name", label: "Name", type: "text", required: true },
      { name: "area", label: "Area", type: "text" },
      { name: "city", label: "City", type: "text" },
      { name: "state", label: "State", type: "text" },
      { name: "phone", label: "Phone", type: "text" },
      { name: "status", label: "Status", type: "select", options: STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: ["name", "area", "city", "state", "phone", "status"],
    searchCols: ["name", "area", "city", "state", "phone"],
    orderBy: "id",
    orderDir: "DESC",
  },

  flight_bookings: {
    key: "flight_bookings",
    table: "flight_bookings",
    label: "Flight Booking",
    plural: "Flight Bookings",
    description: "Air ticket bookings with complete passenger details.",
    fields: [
      { name: "booking_number", label: "Booking Number", type: "text" },
      { name: "passenger_name", label: "Passenger Name", type: "text", required: true },
      { name: "phone", label: "Passenger Phone", type: "text", required: true },
      { name: "passenger_age", label: "Passenger Age", type: "number" },
      { name: "passenger_gender", label: "Gender", type: "select", options: ["Male", "Female", "Other"] },
      { name: "passport_id", label: "Passport / Govt ID", type: "text" },
      { name: "ticket_number", label: "Ticket Number", type: "text" },
      { name: "seat_number", label: "Seat Number", type: "text" },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "booking_date", label: "Booking Date", type: "date" },
      { name: "travel_date", label: "Travel Date", type: "date" },
      { name: "from_location", label: "From", type: "text" },
      { name: "to_location", label: "To", type: "text" },
      { name: "airline", label: "Airline", type: "text" },
      { name: "flight_number", label: "Flight Number", type: "text" },
      { name: "flight_time", label: "Flight Time", type: "time" },
      { name: "pnr", label: "PNR", type: "text" },
      { name: "pax", label: "No. of Passengers", type: "number" },
      { name: "amount", label: "Amount", type: "money" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "booking_number",
      "passenger_name",
      "phone",
      "travel_date",
      "airline",
      "flight_number",
      "from_location",
      "to_location",
      "amount",
    ],
    searchCols: [
      "passenger_name",
      "booking_number",
      "pnr",
      "airline",
      "flight_number",
      "phone",
    ],
    orderBy: "id",
    orderDir: "DESC",
  },

  train_bookings: {
    key: "train_bookings",
    table: "train_bookings",
    label: "Train Booking",
    plural: "Train Bookings",
    description: "Railway ticket bookings with calendar view & passenger client history.",
    fields: [
      { name: "booking_number", label: "Booking Number", type: "text" },
      { name: "passenger_name", label: "Passenger Name", type: "text", required: true },
      { name: "passenger_phone", label: "Passenger Phone", type: "text" },
      { name: "passenger_age", label: "Passenger Age", type: "number" },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "booking_date", label: "Booking Date", type: "date" },
      { name: "travel_date", label: "Travel Date (Calendar)", type: "date" },
      { name: "from_location", label: "From", type: "text" },
      { name: "to_location", label: "To", type: "text" },
      {
        name: "class",
        label: "Class",
        type: "select",
        options: ["1AC", "2AC", "3AC", "SL", "CC", "EC", "2S", "General"],
      },
      { name: "train_number", label: "Train Number / Name", type: "text" },
      { name: "seat_berth", label: "Seat / Berth No.", type: "text" },
      { name: "pnr", label: "PNR Number", type: "text" },
      { name: "amount", label: "Ticket Amount", type: "money" },
      { name: "ticket_status", label: "Ticket Status", type: "select", options: ["Confirmed", "RAC", "Waiting", "Cancelled"] },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "booking_number",
      "passenger_name",
      "travel_date",
      "train_number",
      "class",
      "from_location",
      "to_location",
      "pnr",
      "amount",
    ],
    searchCols: ["passenger_name", "booking_number", "pnr", "train_number", "from_location", "to_location"],
    orderBy: "id",
    orderDir: "DESC",
  },

  bus_bookings: {
    key: "bus_bookings",
    table: "bus_bookings",
    label: "Bus Booking",
    plural: "Bus Bookings",
    description: "Bus ticket bookings with passenger details & payment tracking.",
    fields: [
      { name: "booking_number", label: "Booking Number", type: "text" },
      { name: "passenger_name", label: "Passenger Name", type: "text", required: true },
      { name: "passenger_phone", label: "Passenger Phone", type: "text", required: true },
      { name: "passenger_age", label: "Passenger Age", type: "number" },
      { name: "seat_number", label: "Seat Number", type: "text" },
      {
        name: "customer_id",
        label: "Customer",
        type: "reference",
        ref: "customers",
        refLabel: "name",
      },
      { name: "booking_date", label: "Booking Date", type: "date" },
      { name: "travel_date", label: "Travel Date", type: "date" },
      { name: "from_location", label: "From", type: "text" },
      { name: "to_location", label: "To", type: "text" },
      { name: "travel_time", label: "Travel Time", type: "time" },
      { name: "travels", label: "Travels / Operator", type: "text" },
      { name: "bus_number", label: "Bus Number", type: "text" },
      { name: "pnr", label: "PNR", type: "text" },
      { name: "amount", label: "Ticket Amount", type: "money" },
      { name: "due_amount", label: "Due Amount", type: "money" },
      { name: "payment_status", label: "Payment Status", type: "select", options: PAYMENT_STATUS },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "booking_number",
      "passenger_name",
      "passenger_phone",
      "travel_date",
      "travels",
      "from_location",
      "to_location",
      "amount",
      "payment_status",
    ],
    searchCols: [
      "passenger_name",
      "booking_number",
      "pnr",
      "bus_number",
      "travels",
    ],
    orderBy: "id",
    orderDir: "DESC",
  },

  vehicles: {
    key: "vehicles",
    table: "vehicles",
    label: "Vehicle",
    plural: "Vehicle Registry",
    description:
      "Full fleet registry — website display + number, status, insurance & permit dates.",
    fields: [
      {
        name: "name",
        label: "Vehicle Name",
        type: "text",
        required: true,
        hint: "e.g. Toyota Innova Crysta",
      },
      { name: "vehicle_number", label: "Vehicle Number", type: "text", hint: "e.g. KA-01-AB-1234" },
      {
        name: "category",
        label: "Category",
        type: "select",
        options: VEHICLE_TYPES,
        required: true,
      },
      { name: "vehicle_type", label: "Vehicle Type", type: "select", options: VEHICLE_TYPES },
      { name: "model", label: "Model", type: "text" },
      { name: "variant", label: "Variant", type: "text" },
      { name: "seats", label: "Seats", type: "number" },
      { name: "seating_capacity", label: "Seating Capacity", type: "number" },
      { name: "price_per_km", label: "Price / KM", type: "money" },
      { name: "status", label: "Status", type: "select", options: VEHICLE_STATUS },
      {
        name: "assigned_driver_id",
        label: "Assigned Driver",
        type: "reference",
        ref: "drivers",
        refLabel: "driver_name",
      },
      { name: "purchase_date", label: "Purchase Date", type: "date" },
      { name: "insurance_expiry", label: "Insurance Expiry", type: "date" },
      { name: "permit_expiry", label: "Permit Expiry", type: "date" },
      { name: "fitness_expiry", label: "Fitness Expiry", type: "date" },
      { name: "notes", label: "Notes", type: "textarea" },
    ],
    tableColumns: [
      "name",
      "vehicle_number",
      "category",
      "status",
      "insurance_expiry",
      "permit_expiry",
      "assigned_driver_id",
    ],
    searchCols: ["name", "vehicle_number", "model", "variant"],
    orderBy: "name",
    orderDir: "ASC",
    insertDefaults: {
      slug: "vehicle",
      luggage: "",
      features: [],
      image: "/images/fleet/car-sedan.jpg",
      description: "",
      is_popular: false,
      seats: 4,
      price_per_km: 0,
    },
  },
};

export function getResourceConfig(key: string): ResourceConfig | undefined {
  return BUSINESS_RESOURCES[key];
}

export function isResourceWhitelisted(key: string): boolean {
  return key in BUSINESS_RESOURCES;
}

export function coerceValue(field: FieldDef, raw: unknown): unknown {
  if (raw === undefined || raw === null) return null;
  if (typeof raw === "string" && raw.trim() === "") return null;

  switch (field.type) {
    case "number":
    case "money": {
      const n = parseFloat(String(raw));
      return Number.isNaN(n) ? null : n;
    }
    case "boolean":
      return raw === true || raw === "true" || raw === "on" || raw === 1 || raw === "1";
    case "date":
    case "time":
    case "text":
    case "email":
    case "textarea":
    case "select":
    case "reference":
    default:
      return typeof raw === "string" ? raw : String(raw ?? "");
  }
}
