/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TourPackagesRouteImport } from './routes/tour-packages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as CarRentalsRouteImport } from './routes/car-rentals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourPackagesPackageIdRouteImport } from './routes/tour-packages.$packageId'
import { Route as CarRentalsVehicleIdRouteImport } from './routes/car-rentals.$vehicleId'

const TourPackagesRoute = TourPackagesRouteImport.update({
  id: '/tour-packages',
  path: '/tour-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRentalsRoute = CarRentalsRouteImport.update({
  id: '/car-rentals',
  path: '/car-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesPackageIdRoute = TourPackagesPackageIdRouteImport.update({
  id: '/$packageId',
  path: '/$packageId',
  getParentRoute: () => TourPackagesRoute,
} as any)
const CarRentalsVehicleIdRoute = CarRentalsVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => CarRentalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/car-rentals': typeof CarRentalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tour-packages': typeof TourPackagesRouteWithChildren
  '/car-rentals/$vehicleId': typeof CarRentalsVehicleIdRoute
  '/tour-packages/$packageId': typeof TourPackagesPackageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/car-rentals': typeof CarRentalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tour-packages': typeof TourPackagesRouteWithChildren
  '/car-rentals/$vehicleId': typeof CarRentalsVehicleIdRoute
  '/tour-packages/$packageId': typeof TourPackagesPackageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/car-rentals': typeof CarRentalsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tour-packages': typeof TourPackagesRouteWithChildren
  '/car-rentals/$vehicleId': typeof CarRentalsVehicleIdRoute
  '/tour-packages/$packageId': typeof TourPackagesPackageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/car-rentals'
    | '/sitemap.xml'
    | '/tour-packages'
    | '/car-rentals/$vehicleId'
    | '/tour-packages/$packageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/car-rentals'
    | '/sitemap.xml'
    | '/tour-packages'
    | '/car-rentals/$vehicleId'
    | '/tour-packages/$packageId'
  id:
    | '__root__'
    | '/'
    | '/car-rentals'
    | '/sitemap.xml'
    | '/tour-packages'
    | '/car-rentals/$vehicleId'
    | '/tour-packages/$packageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarRentalsRoute: typeof CarRentalsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TourPackagesRoute: typeof TourPackagesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tour-packages': {
      id: '/tour-packages'
      path: '/tour-packages'
      fullPath: '/tour-packages'
      preLoaderRoute: typeof TourPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-rentals': {
      id: '/car-rentals'
      path: '/car-rentals'
      fullPath: '/car-rentals'
      preLoaderRoute: typeof CarRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/$packageId': {
      id: '/tour-packages/$packageId'
      path: '/$packageId'
      fullPath: '/tour-packages/$packageId'
      preLoaderRoute: typeof TourPackagesPackageIdRouteImport
      parentRoute: typeof TourPackagesRoute
    }
    '/car-rentals/$vehicleId': {
      id: '/car-rentals/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/car-rentals/$vehicleId'
      preLoaderRoute: typeof CarRentalsVehicleIdRouteImport
      parentRoute: typeof CarRentalsRoute
    }
  }
}

interface CarRentalsRouteChildren {
  CarRentalsVehicleIdRoute: typeof CarRentalsVehicleIdRoute
}

const CarRentalsRouteChildren: CarRentalsRouteChildren = {
  CarRentalsVehicleIdRoute: CarRentalsVehicleIdRoute,
}

const CarRentalsRouteWithChildren = CarRentalsRoute._addFileChildren(
  CarRentalsRouteChildren,
)

interface TourPackagesRouteChildren {
  TourPackagesPackageIdRoute: typeof TourPackagesPackageIdRoute
}

const TourPackagesRouteChildren: TourPackagesRouteChildren = {
  TourPackagesPackageIdRoute: TourPackagesPackageIdRoute,
}

const TourPackagesRouteWithChildren = TourPackagesRoute._addFileChildren(
  TourPackagesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarRentalsRoute: CarRentalsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TourPackagesRoute: TourPackagesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
