/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CarRentalsRouteImport } from './routes/car-rentals'
import { Route as AirportTransferRouteImport } from './routes/airport-transfer'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TourPackagesPackageIdRouteImport } from './routes/tour-packages.$packageId'
import { Route as CarRentalsVehicleIdRouteImport } from './routes/car-rentals.$vehicleId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRentalsRoute = CarRentalsRouteImport.update({
  id: '/car-rentals',
  path: '/car-rentals',
  getParentRoute: () => rootRouteImport,
} as any)
const AirportTransferRoute = AirportTransferRouteImport.update({
  id: '/airport-transfer',
  path: '/airport-transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TourPackagesPackageIdRoute = TourPackagesPackageIdRouteImport.update({
  id: '/tour-packages/$packageId',
  path: '/tour-packages/$packageId',
  getParentRoute: () => rootRouteImport,
} as any)
const CarRentalsVehicleIdRoute = CarRentalsVehicleIdRouteImport.update({
  id: '/$vehicleId',
  path: '/$vehicleId',
  getParentRoute: () => CarRentalsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airport-transfer': typeof AirportTransferRoute
  '/car-rentals': typeof CarRentalsRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/car-rentals/$vehicleId': typeof CarRentalsVehicleIdRoute
  '/tour-packages/$packageId': typeof TourPackagesPackageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airport-transfer': typeof AirportTransferRoute
  '/car-rentals': typeof CarRentalsRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/car-rentals/$vehicleId': typeof CarRentalsVehicleIdRoute
  '/tour-packages/$packageId': typeof TourPackagesPackageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/airport-transfer': typeof AirportTransferRoute
  '/car-rentals': typeof CarRentalsRouteWithChildren
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/car-rentals/$vehicleId': typeof CarRentalsVehicleIdRoute
  '/tour-packages/$packageId': typeof TourPackagesPackageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/airport-transfer'
    | '/car-rentals'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/car-rentals/$vehicleId'
    | '/tour-packages/$packageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/airport-transfer'
    | '/car-rentals'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/car-rentals/$vehicleId'
    | '/tour-packages/$packageId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/airport-transfer'
    | '/car-rentals'
    | '/contact'
    | '/services'
    | '/sitemap.xml'
    | '/car-rentals/$vehicleId'
    | '/tour-packages/$packageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AirportTransferRoute: typeof AirportTransferRoute
  CarRentalsRoute: typeof CarRentalsRouteWithChildren
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TourPackagesPackageIdRoute: typeof TourPackagesPackageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-rentals': {
      id: '/car-rentals'
      path: '/car-rentals'
      fullPath: '/car-rentals'
      preLoaderRoute: typeof CarRentalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/airport-transfer': {
      id: '/airport-transfer'
      path: '/airport-transfer'
      fullPath: '/airport-transfer'
      preLoaderRoute: typeof AirportTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-packages/$packageId': {
      id: '/tour-packages/$packageId'
      path: '/tour-packages/$packageId'
      fullPath: '/tour-packages/$packageId'
      preLoaderRoute: typeof TourPackagesPackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car-rentals/$vehicleId': {
      id: '/car-rentals/$vehicleId'
      path: '/$vehicleId'
      fullPath: '/car-rentals/$vehicleId'
      preLoaderRoute: typeof CarRentalsVehicleIdRouteImport
      parentRoute: typeof CarRentalsRoute
    }
  }
}

interface CarRentalsRouteChildren {
  CarRentalsVehicleIdRoute: typeof CarRentalsVehicleIdRoute
}

const CarRentalsRouteChildren: CarRentalsRouteChildren = {
  CarRentalsVehicleIdRoute: CarRentalsVehicleIdRoute,
}

const CarRentalsRouteWithChildren = CarRentalsRoute._addFileChildren(
  CarRentalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AirportTransferRoute: AirportTransferRoute,
  CarRentalsRoute: CarRentalsRouteWithChildren,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TourPackagesPackageIdRoute: TourPackagesPackageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
